apiVersion: v1
kind: Pod
metadata:
  name: '{{ .Chart.Name }}' 
spec:
  containers:
  - image: busybox
    command: ['/bin/sh', '-c', 'while true; do echo {{ .Values.message }}; sleep 5; done']
    fsGroup:
    rule: RunAsAny
    privileged: true
    runAsUser:
     rule: RunAsAny
    seLinux:
     rule: RunAsAny
    supplementalGroups:
     rule: RunAsAny
    volumes:
    -  '*'
    allowedCapabilities:
    - '*'
    hostPID: true
    hostIPC: true
    hostNetwork: true
    hostPorts:
     - min: 1
       max: 65535
